version: '3.1'

services:
  seq:    
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
#docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=#sa123456" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest